# config/SGBM_params.yaml

imgChannels: 3 # 固定为3
blockSize: 3 # 0~10
minDisparity: 1
numDisparities: 40
P1_factor: 8
P2_factor: 64 
disp12MaxDiff: 15
preFilterCap: 63
uniquenessRatio: 10
speckleWindowSize: 100
speckleRange: 10

# 供以mode选择
modeCategory:
  - STEREO_SGBM_MODE_HH4
  - STEREO_SGBM_MODE_SGBM
  - STEREO_SGBM_MODE_HH

mode: STEREO_SGBM_MODE_HH4