# config/SGBM_params.yaml

imgChannels: 3 # 固定为3
blockSize: 5 # 区块大小，必须是奇数，通常在3-11之间
minDisparity: 0
numDisparities: 96 # 必须是16的倍数
P1_factor: 8
P2_factor: 64 
disp12MaxDiff: 1
preFilterCap: 63
uniquenessRatio: 10
speckleWindowSize: 100
speckleRange: 10

# 供以mode选择
modeCategory:
  - STEREO_SGBM_MODE_HH4
  - STEREO_SGBM_MODE_SGBM
  - STEREO_SGBM_MODE_HH

mode: STEREO_SGBM_MODE_SGBM